In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
covdat=pd.read_csv('C:\ML Algos\covidsymptomsdata.csv')

In [3]:
covdat.head()

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Male  Gender_Transgender  Severity_Mild  Severity_Moderate  \
0            1                   0              1                  0   
1            1                   0              1                  0   
2            1                   0              1                  0   
3            1                   0              0                  1   
4            1                   0              0                  1   

   Severity_None  Severity_Severe  Contact_Dont-Know  Contact_No  Contact_Yes  \
0              0                0                  0           0            1   
1              0                0                  0           1            0   
2              0                0                  1           0            0   
3              0                0                  0           0            1   
4              0                0                  0           1            0   

   Country  
0    China  
1    China  
2    China  
3    China  
4    China  

[5 rows x 27 columns]

In [4]:
covdat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 27 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   Fever                    316800 non-null  int64 
 1   Tiredness                316800 non-null  int64 
 2   Dry-Cough                316800 non-null  int64 
 3   Difficulty-in-Breathing  316800 non-null  int64 
 4   Sore-Throat              316800 non-null  int64 
 5   None_Sympton             316800 non-null  int64 
 6   Pains                    316800 non-null  int64 
 7   Nasal-Congestion         316800 non-null  int64 
 8   Runny-Nose               316800 non-null  int64 
 9   Diarrhea                 316800 non-null  int64 
 10  None_Experiencing        316800 non-null  int64 
 11  Age_0-9                  316800 non-null  int64 
 12  Age_10-19                316800 non-null  int64 
 13  Age_20-24                316800 non-null  int64 
 14  Age_25-59           

In [21]:
covdat['Target'] = 0
covdat.head()

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Transgender  Severity_Mild  Severity_Moderate  Severity_None  \
0                   0              1                  0              0   
1                   0              1                  0              0   
2                   0              1                  0              0   
3                   0              0                  1              0   
4                   0              0                  1              0   

   Severity_Severe  Contact_Dont-Know  Contact_No  Contact_Yes  Country  \
0                0                  0           0            1    China   
1                0                  0           1            0    China   
2                0                  1           0            0    China   
3                0                  0           0            1    China   
4                0                  0           1            0    China   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0  

[5 rows x 28 columns]

In [26]:
conditions=[(covdat['Severity_None']==1),(covdat['Severity_Mild']==1),(covdat['Severity_Moderate']==1),(covdat['Severity_Severe']==1),]
values=[0,1,2,3]
covdat['Target']=np.select(conditions,values)
print(covdat)

        Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0           1          1          1                        1            1   
1           1          1          1                        1            1   
2           1          1          1                        1            1   
3           1          1          1                        1            1   
4           1          1          1                        1            1   
...       ...        ...        ...                      ...          ...   
316795      0          0          0                        0            0   
316796      0          0          0                        0            0   
316797      0          0          0                        0            0   
316798      0          0          0                        0            0   
316799      0          0          0                        0            0   

        None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \

In [27]:
covdat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 28 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   Fever                    316800 non-null  int64 
 1   Tiredness                316800 non-null  int64 
 2   Dry-Cough                316800 non-null  int64 
 3   Difficulty-in-Breathing  316800 non-null  int64 
 4   Sore-Throat              316800 non-null  int64 
 5   None_Sympton             316800 non-null  int64 
 6   Pains                    316800 non-null  int64 
 7   Nasal-Congestion         316800 non-null  int64 
 8   Runny-Nose               316800 non-null  int64 
 9   Diarrhea                 316800 non-null  int64 
 10  None_Experiencing        316800 non-null  int64 
 11  Age_0-9                  316800 non-null  int64 
 12  Age_10-19                316800 non-null  int64 
 13  Age_20-24                316800 non-null  int64 
 14  Age_25-59           

In [29]:
X = covdat.iloc[:20000,:18]
X.head()

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  \
0             0      1                 1           1         1   
1             0      1                 1           1         1   
2             0      1                 1           1         1   
3             0      1                 1           1         1   
4             0      1                 1           1         1   

   None_Experiencing  Age_0-9  Age_10-19  Age_20-24  Age_25-59  Age_60+  \
0                  0        1          0          0          0        0   
1                  0        1          0          0          0        0   
2                  0        1          0          0          0        0   
3                  0        1          0          0          0        0   
4                  0        1          0          0          0        0   

   Gender_Female  Gender_Male  
0              0            1  
1              0            1  
2              0            1  
3              0            1  
4              0            1

In [30]:
y = covdat.iloc[:20000,27]
y

0        1
1        1
2        1
3        2
4        2
        ..
19995    2
19996    2
19997    2
19998    3
19999    3
Name: Target, Length: 20000, dtype: int32

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [32]:
from sklearn.svm import SVC
svmobj=SVC()
svmobj.fit(X_train,y_train)
y_pred=svmobj.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [34]:
print(f"Accuracy:-{accuracy_score(y_test,y_pred)}")

Accuracy:-0.15


In [35]:
print(confusion_matrix(y_test,y_pred))

[[130 168 341 355]
 [241  93 329 376]
 [241 203 183 371]
 [248 184 343 194]]


In [36]:
print(classification_report)

<function classification_report at 0x00000231033DF8B0>


In [37]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=100)
knn.fit(X_train,y_train)


KNeighborsClassifier(n_neighbors=100)

In [38]:
knn.score(X_test,y_test)

0.19275

In [39]:
y_pred=knn.predict(X_test)
print(confusion_matrix(y_test,y_pred))

[[218 274 254 248]
 [326 201 273 239]
 [316 255 188 239]
 [302 253 250 164]]


In [40]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train,y_train)

LogisticRegression()

In [41]:
LR.score(X_test,y_test)

0.23025